openapi: 3.0.1

info:
  title: ERP 預約系統
  version: 1.0.0
  description: ERP 預約系統相關 API

tags:
  - name: booking
    description: 預約系統相關API

# 這裡可以選擇網域
servers:
  - url: http://localhost:8000/project/public/api/sync/

components:
  # 定義一些 auth 認證的 token
  securitySchemes:
    token:
      in: header
      type: apiKey
      name: Authorization
      description: 驗證需要的token
  # 定義一些通用參數避免繁複定義
  parameters:
    language:
      in: header
      name: accept-language
      schema:
        type: string
      required: false
      example: 'en'
  schemas:
    CreateBooking:
      type: object
      required:
        - contact_uuid
        - contact_name
        - contact_mobile
        - contact_email
        - product_specific_sys_activity_id
      properties:
        contact_uuid:
          type: string
          description: required, 顧客 UUID
          format: uuid
          example: e475e794-8105-11ed-a6ed-0242ac170005
        contact_name:
          type: string
          description: required, 顧客姓名
          example: Next Gen
        contact_mobile:
          type: string
          description: required, 顧客手機
        contact_email:
          type: string
          description: required, 顧客 email
        product_specific_sys_activity_id:
          type: integer
          description: required, ERP 活動場次 ID
          example: 6
        # staff_id:
        #   type: integer
        #   description: 服務生ID
        # user_id:
        #   type: integer
        #   description: 服務生ID
        res_waiter_id:
          type: integer
          description: optional, 服務生ID
        business_id:
          type: integer
          description: only required in ERP, 總店ID
        location_id:
          type: integer
          description: only required in ERP, 分店ID
        contact_id:
          type: integer
          description: only required in ERP, 顧客ID
        booking_start:
          type: string
          description: 預約開始時間
        booking_end:
          type: string
          description: 預約結束時間
        booking_note:
          type: string
          description: 預約備註
          example: 海景第一排
        payment_status:
          type: string
          description: 付款狀態
          example: unpaid
          default: unpaid
    CreateBookingResp:
      type: object
      properties:
        success:
          type: boolean
          description: 執行結果(1=成功, 0=失敗)
        msg:
          type: string
          description: 結果訊息
    UpdateBooking:
      type: object
      properties:
        location_id:
          type: integer
          description: 分店ID
        res_waiter_id:
          type: integer
          description: 服務生ID
        booking_start:
          type: string
          description: 預約開始時間
        booking_end:
          type: string
          description: 預約結束時間
        product_specific_sys_activity_id:
          type: integer
          description: 活動相關ID
    UpdateBookingResp:
      type: object
      properties:
        success:
          type: boolean
          description: 執行結果(1=成功, 0=失敗)
        msg:
          type: string
          description: 結果訊息
    DeleteBookingResp:
      type: object
      properties:
        success:
          type: boolean
          description: 執行結果(1=成功, 0=失敗)
        msg:
          type: string
          description: 結果訊息
    ServiceStaffResponse:
      type: object
      properties:
        success:
          type: boolean
        date:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                description: 服務人員ID
              full_name:
                type: string
                description: 服務人員名稱
              email:
                type: string
                description: 服務人員email
    ProductSpecificSysActivity:
      type: object
      properties:
        product_specific_sys_activity_id:
          type: integer
          description: 活動ID
        user_id:
          type: integer
          description: 服務人員ID
        start_time:
          type: string
          format: ISO8601:2004
          description: 活動開始時間
          example: "2023-02-07T08:00:00+80:00"
        end_time:
          type: string
          format: ISO8601:2004
          description: 活動結束時間
          example: "2023-02-07T09:00:00+80:00"
    SingleServiceStaffResp:
      type: object
      properties:
        id:
          type: integer
          description: 服務人員ID
        full_name:
          type: string
          description: 服務人員名稱
        email:
          type: string
          description: 服務人員 email
        product_specific_sys_activities:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/ProductSpecificSysActivity'

paths:
  /booking/service-staff:
    get:
      summary: 取得服務人員列表
      description: 取得服務人員
      # 分類
      tags:
        - booking
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceStaffResponse'
              example:
                success: 1
                data:
                  - id: 1
                    full_name: Service Staff A
                    email: waiter1@nextgen.com.hk
                  - id: 2
                    full_name: Service Staff B
                    email: waiter2@nextgen.com.hk



  /booking/service-staff/{id}:
    get:
      summary: 服務人員詳細資訊及可預約場次
      description: 取得指定服務人員詳細資訊及可預約場次
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the user to return.
          schema:
            type: integer
            format: int64
            minimum: 1
      # 分類
      tags:
        - booking
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SingleServiceStaffResp'
              example:
                success: 1
                data:
                - id: 1
                  full_name: Service Staff A
                  email: waiter1@nextgen.com.hk
                  product_specific_sys_activities:
                    - product_specific_sys_activity_id: 1
                      user_id: 5
                      start_time: "2023-02-07T08:00:00+80:00"
                      end_time: "2023-02-07T09:00:00+80:00"
                    - product_specific_sys_activity_id: 2
                      user_id: 5
                      start_time: "2023-02-07T09:00:00+80:00"
                      end_time: "2023-02-07T10:00:00+80:00"

  /booking:
    post:
      summary: 新增預約
      description: 新增預約
      tags:
        - booking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBooking'
            example:
              contact_name: 王小明
              contact_mobile: 0912654987
              contact_email: "wangming@nextgen.com.hk"
              contact_uuid: e475e794-8105-11ed-a6ed-0242ac170005
              product_specific_sys_activity_id: 8
              res_waiter_id: 5

      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateBookingResp'
              example:
                success: 1
                msg: Added success
    get:
      summary: 取得預約列表
      description: 取得預約列表
      parameters:
        - name: customer_id
          in: query
          # required: true
          description: The ID of the user.
          schema:
            type: integer
            format: int64
            minimum: 1
      tags:
        - booking
      responses:
        '200':
          description: 成功
  /booking/{booking_id}:
    put:
      summary: 更新顧客預約
      description: 更新顧客預約
      parameters:
        - name: booking_id
          in: path
          required: true
          description: The ID of the booking.
          schema:
            type: integer
            format: int64
            minimum: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateBooking'
            example:
              location_id: 1
              res_waiter_id: 5
              booking_start: "02/10/2023 15:40"
              booking_end: "02/10/2023 15:45"
              product_specific_sys_activity_id: 8
      tags:
        - booking
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateBookingResp'
              example:
                success: 1
                msg: update success

    delete:
      summary: 刪除顧客預約
      description: 刪除顧客預約
      parameters:
        - name: booking_id
          in: path
          required: true
          description: The ID of the booking.
          schema:
            type: integer
            format: int64
            minimum: 1
      tags:
        - booking
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteBookingResp'
              example:
                success: 1
                msg: delete success


  /product/{uuid}/{start_time}/{end_time}:
    get:
      summary: 服務人員詳細資訊及可預約場次
      description: 取得指定服務人員詳細資訊及可預約場次
      tags:
        - booking
      parameters:
        - name: uuid
          in: path
          required: true
          description: ERP Product uuid
          schema:
            type: string
            format: uuid
          example: 703e2de9-b330-11ed-b4f9-0242ac170002
        - name: start_time
          in: path
          required: true
          description: 查詢起始時間。Timestamp, 秒級
          schema:
            type: integer
            format: timestamp
          example: 1675180800
        - name: end_time
          in: path
          required: true
          description: 查詢結束時間。Timestamp, 秒級
          schema:
            type: integer
            format: timestamp
          example: 1677599999
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: 成功 = true, 失敗 = false
                  data:
                    type: object
                    description: 回傳的資料
                    properties:
                      product_specific_sys_activities:
                        type: array
                        description: 活動場次資料的陣列
                        items:
                          type: object
                          description: 活動場次資料
                          $ref: '#/components/schemas/ProductSpecificSysActivity'
              example:
                success: 1
                data:
                  product_specific_sys_activities:
                    - product_specific_sys_activity_id: 1
                      user_id: 5
                      start_time: "2023-02-07T08:00:00+80:00"
                      end_time: "2023-02-07T09:00:00+80:00"
                    - product_specific_sys_activity_id: 2
                      user_id: 5
                      start_time: "2023-02-07T09:00:00+80:00"
                      end_time: "2023-02-07T10:00:00+80:00"
