openapi: 3.0.1

info:
  title: POS 新 Layout
  version: 1.0.0
  description: POS新Layout相關API

servers:
  - url: http://localhost:8000/project/public/pos-v2
  - url: https://erp-dev.cloudsatlas.com.hk/public

tags:
  - name: POS V2
    description: 新版POS相關API
  - name: POS V1
    description: 原生POS相關API

components:
  parameters:
    language:
      in: header
      name: accept-language
      schema:
        type: string
      required: false
      example: 'en'
  schemas:
    CustomersResponse:
      type: array
      items:
        type: object
        properties:
          id:
            type: number
            description: 客戶ID
          text:
            type: string
            description: 客戶名稱及ID
          mobile:
            type: string
            description: 手機
          address_line_1:
            type: string
            description: 地址1
          address_line_2:
            type: string
            description: 地址2
          city:
            type: string
          state:
            type: string
          country:
            type: string
          zip_code:
            type: string
          shipping_address:
            type: string
            description: 收件地址
          pay_term_number:
            type: string
          pay_term_type:
            type: string
          balance:
            type: string
          supplier_business_name:
            type: string
            description: 供應商名稱
          discount_percent:
            type: string
          price_calculation_type:
            type: string
          selling_price_group_id:
            type: string
          shipping_custom_field_details:
            type: string
          is_export:
            type: number
          export_custom_field_1:
            type: string
          export_custom_field_2:
            type: string
          export_custom_field_3:
            type: string
          export_custom_field_4:
            type: string
          export_custom_field_5:
            type: string
          export_custom_field_6:
            type: string
    ProductsResponse:
      type: array
      items:
        type: object
        properties:
          product_id:
            type: number
            description: 產品ID
          name:
            type: string
            description: 產品名稱
          type:
            type: string
            description: 產品類型
          enable_stock:
            type: boolean
            description: 是否啟用庫存管理
          variation_id:
            type: integer
            description: 產品衍生規格ID
          variation:
            type: string
            description: 衍生規格名稱
          selling_price:
            type: string
            description: 售價
          sub_sku:
            type: string
            description: Sub SKU
          unit:
            type: string
            description: 單位
          purchase_line_id:
            type: string
            description: 採購單ID
          lot_number:
            type: string
            description: 批號
          image_url:
            type: string
            description: 圖片URL
    SuspendTxnResponse:
      type: array
      items:
        type: object
        properties:
          id:
            type: number
          transaction_date:
            type: string
          type:
            type: string
          is_direct_sale:
            type: number
          invoice_no:
            type: string
          invoice_no_text:
            type: string
          name:
            type: string
          mobile:
            type: string
          contact_id:
            type: string
          supplier_business_name:
            type: string
            description: xxx
          status:
            type: string
          payment_status:
            type: string
          final_total:
            type: string
          tax_amount:
            type: string
          discount_amount:
            type: string
          discount_type:
            type: string
          total_before_tax:
            type: string
          rp_redeemed:
            type: number
          rp_redeemed_amount:
            type: string
          rp_earned:
            type: number
          types_of_service_id:
            type: integer
            description: xxx
          shipping_status:
            type: string
            description: xxxx
          pay_term_number:
            type: integer
            description: xxx
          pay_term_type:
            type: string
            description: xxx
          additional_notes:
            type: string
            description: xxx
          staff_note:
            type: string
            description: xxx
          shipping_details:
            type: string
            description: xxx
          document:
            type: string
            description: xxx
          shipping_custom_field_1:
            type: string
            description: xxx
          shipping_custom_field_2:
            type: string
            description: xxx
          shipping_custom_field_3:
            type: string
            description: xxx
          shipping_custom_field_4:
            type: string
            description: xxx
          shipping_custom_field_5:
            type: string
            description: xxx
          custom_field_1:
            type: string
            description: xxx
          custom_field_2:
            type: string
            description: xxx
          custom_field_3:
            type: string
            description: xxx
          custom_field_4:
            type: string
            description: xxx
          sale_date:
            type: string
          added_by:
            type: string
          total_paid:
            type: integer
            description: xxxx
          business_location:
            type: string
          return_exists:
            type: number
          return_paid:
            type: integer
            description: xxx
          amount_return:
            type: string
          return_transaction_id:
            type: integer
            description: xxx
          types_of_service_name:
            type: string
            description: xxx
          service_custom_field_1:
            type: string
            description: xxx
          total_items:
            type: number
          waiter:
            type: string
          table_name:
            type: string
            description: xxx
          so_qty_remaining:
            type: string
          is_export:
            type: number
          shipping_location_to:
            type: string
            description: xxx
          shipping_etd:
            type: string
            description: xxx
          shipping_eta:
            type: string
            description: xxx
          shipping_atd:
            type: string
            description: xxx
          shipping_ata:
            type: string
            description: xxx
          shipping_round_trip:
            type: string
            description: xxx
          driver_id:
            type: integer
            description: xxx
          transporter_id:
            type: integer
            description: xxx
          shipping_address:
            type: string
            description: xxx
          delivered_to:
            type: string
            description: xxx
          is_medicine:
            type: number
          crm_is_order_request:
            type: number
          is_suspend:
            type: number
          res_table_id:
            type: integer
            description: xxx
          res_waiter_id:
            type: integer
            description: xxx
          sell_lines:
            type: array
            items:
              type: object
              properties:
                id:
                  type: number
                transaction_id:
                  type: number
                product_id:
                  type: number
                variation_id:
                  type: number
                quantity:
                  type: number
                mfg_waste_percent:
                  type: string
                mfg_ingredient_group_id:
                  type: integer
                  description: xxx
                quantity_returned:
                  type: string
                unit_price_before_discount:
                  type: string
                unit_price:
                  type: string
                line_discount_type:
                  type: string
                line_discount_amount:
                  type: string
                unit_price_inc_tax:
                  type: string
                item_tax:
                  type: string
                tax_id:
                  type: integer
                  description: xxx
                discount_id:
                  type: integer
                  description: xxx
                lot_no_line_id:
                  type: integer
                  description: xxx
                sell_line_note:
                  type: string
                so_line_id:
                  type: integer
                  description: xxx
                so_quantity_invoiced:
                  type: string
                res_service_staff_id:
                  type: integer
                  description: xxx
                res_line_order_status:
                  type: string
                  description: xxx
                parent_sell_line_id:
                  type: string
                  description: xxx
                children_type:
                  type: string
                sub_unit_id:
                  type: integer
                  description: xxx
                created_at:
                  type: string
                updated_at:
                  type: string
          table:
            type: string
            description: xxx
          service_staff:
            type: string
            description: xxx
    CustomTagsResponse:
      type: object
      properties:
        success:
          type: boolean
        msg:
          type: string
        data:
          type: object
          properties:
            1:
              type: string
              description: 自訂產品標籤1
            2:
              type: string
              description: 自訂產品標籤2
            3:
              type: string
              description: 自訂產品標籤3
            4:
              type: string
              description: 自訂產品標籤4
            5:
              type: string
              description: 自訂產品標籤5
paths:
  
  /products:
    get:
      summary: 產品清單
      description: 取得產品清單
      tags:
        - POS V2
      parameters:
        - in: query
          name: location_id
          schema:
            type: integer
          description: 營業地點ID
        - in: query
          name: term
          schema:
            type: string
          description: 搜尋關鍵字
        - in: query
          name: tag_id
          schema:
            type: integer
            minimum: 1
            maximum: 5
          description: 客戶自訂產品標籤ID
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductsResponse'
              example:
                - product_id: 70
                  name: 可樂
                  type: single
                  enable_stock: 1
                  variation_id: 119
                  variation: DUMMY
                  qty_available: 2232.0000
                  selling_price: 125.0000
                  sub_sku: 0070
                  unit: Pc(s)
                  purchase_line_id: 70
                  lot_number:
                  image_url: http://localhost:8000/project/public/img/default.png
                - product_id: 71
                  name: 黑松沙士
                  type: single
                  enable_stock: 1
                  variation_id: 120
                  variation: DUMMY
                  qty_available: 1010.0000
                  selling_price: 250.0000
                  sub_sku: 0071
                  unit: Pc(s)
                  purchase_line_id: 68
                  lot_number: Batch111
                  image_url: http://localhost:8000/project/public/img/default.png
  /custom-tags:
    get:
      summary: 客戶自訂產品標籤
      description: 取得客戶自訂產品標籤
      tags:
        - POS V2
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomTagsResponse'
              example:
                success: 1
                msg: "Success"
                data: 
                  1: 熱銷
                  2: 促銷
                  3: 打折
                  4: 清倉
                  5: 週年慶
  /sells:
    get:
      summary: 暫存訂單列表
      description: 取得暫存訂單列表
      tags:
        - POS V1
      parameters:
        - in: query
          name: suspended
          schema:
            type: boolean
          description: 是否為暫存訂單
        - in: query
          name: pos_v2
          schema:
            type: boolean
          description: 是否為新版POS頁面
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuspendTxnResponse'
              example:
                - id: 1
                  text: Walk-in (CO0001)
                  mobile: 0934987146
                  address_line_1:
                  address_line_2:
                  city:
                  state:
                  country:
                  zip_code:
                  shipping_address:
                  pay_term_number:
                  pay_term_type:
                  balance:
                  supplier_business_name:
                  discount_percent:
                  price_calculation_type:
                  selling_price_group_id:
                  shipping_custom_field_details:
                  is_export: 0
                  export_custom_field_1:
                  export_custom_field_2:
                  export_custom_field_3:
                  export_custom_field_4:
                  export_custom_field_5:
                  export_custom_field_6:
                - id: 2
                  text: Miss jojo Lin (CO0002)
                  mobile: 0966123458
                  address_line_1:
                  address_line_2:
                  city:
                  state:
                  country:
                  zip_code:
                  shipping_address:
                  pay_term_number:
                  pay_term_type:
                  balance: 0.0000
                  supplier_business_name:
                  discount_percent:
                  price_calculation_type:
                  selling_price_group_id:
                  shipping_custom_field_details:
                  is_export: 0
                  export_custom_field_1:
                  export_custom_field_2:
                  export_custom_field_3:
                  export_custom_field_4:
                  export_custom_field_5:
                  export_custom_field_6:
  /contacts/customers:
    get:
      summary: 會員清單
      description: 取得會員清單
      tags:
        - POS V1
      parameters:
        - in: query
          name: q
          schema:
            type: string
          description: keyword
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomersResponse'
              example:
                - id: 1
                  text: Walk-in (CO0001)
                  mobile: 0934987146
                  address_line_1:
                  address_line_2:
                  city:
                  state:
                  country:
                  zip_code:
                  shipping_address:
                  pay_term_number:
                  pay_term_type:
                  balance:
                  supplier_business_name:
                  discount_percent:
                  price_calculation_type:
                  selling_price_group_id:
                  shipping_custom_field_details:
                  is_export: 0
                  export_custom_field_1:
                  export_custom_field_2:
                  export_custom_field_3:
                  export_custom_field_4:
                  export_custom_field_5:
                  export_custom_field_6:
                - id: 2
                  text: Miss jojo Lin (CO0002)
                  mobile: 0966123458
                  address_line_1:
                  address_line_2:
                  city:
                  state:
                  country:
                  zip_code:
                  shipping_address:
                  pay_term_number:
                  pay_term_type:
                  balance: 0.0000
                  supplier_business_name:
                  discount_percent:
                  price_calculation_type:
                  selling_price_group_id:
                  shipping_custom_field_details:
                  is_export: 0
                  export_custom_field_1:
                  export_custom_field_2:
                  export_custom_field_3:
                  export_custom_field_4:
                  export_custom_field_5:
                  export_custom_field_6:
  /products/list:
    get:
      summary: 取得產品列表
      description: 在POS頁面的搜尋產品欄輸入關鍵字便會搜尋符合的產品
      tags:
        - POS V1
      parameters:
        - in: query
          name: price_group
          schema:
            type: integer
          description: 價格群組ID
        - in: query
          name: location_id
          schema:
            type: integer
          description: 營業地點ID
        - in: query
          name: term
          schema:
            type: string
          description: 搜尋關鍵字
        - in: query
          name: not_for_selling
          schema:
            type: boolean
            default: false
          description: 是否為非賣品
        - in: query
          name: search_fields
          schema:
            type: array
            items:
              type: string
          description:  搜尋欄位名稱
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductsResponse'
              example:
                - product_id: 70
                  name: 可樂
                  type: single
                  enable_stock: 1
                  variation_id: 119
                  variation: DUMMY
                  qty_available: 2232.0000
                  selling_price: 125.0000
                  sub_sku: 0070
                  unit: Pc(s)
                  purchase_line_id: 70
                  lot_number:
                  image_url: http://localhost:8000/project/public/img/default.png
                - product_id: 71
                  name: 黑松沙士
                  type: single
                  enable_stock: 1
                  variation_id: 120
                  variation: DUMMY
                  qty_available: 1010.0000
                  selling_price: 250.0000
                  sub_sku: 0071
                  unit: Pc(s)
                  purchase_line_id: 68
                  lot_number: Batch111
                  image_url: http://localhost:8000/project/public/img/default.png
  /sells/pos/get-product-suggestion:
    get:
      summary: 取得建議產品列表
      description: 在POS首頁會顯示建議產品的清單
      tags:
        - POS V1
      parameters:
        - in: query
          name: category_id
          schema:
            type: integer
          description: 類別ID
        - in: query
          name: brand_id
          schema:
            type: integer
          description: 品牌ID
        - in: query
          name: location_id
          schema:
            type: integer
            minimum: 1
          description: 營業地點ID
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
          description: 分頁頁數
        - in: query
          name: is_enabled_stock
          schema:
            type: integer
          description:  是否有啟用庫存管理
        - in: query
          name: repair_model_id
          schema:
            type: integer
      responses:
        '200':
          description: 成功，回傳HTML
