openapi: 3.0.1

info:
  title: ERP配藥系統API
  version: 1.0.0
  description: ERP配藥系統API相關說明文件

servers:
  - url: http://localhost:8000/project/public/api
  - url: https://pos.cloudsatlas.com.hk/public/api
  - url: https://erp-dev.cloudsatlas.com.hk/public/api
tags:
  - name: Business
    description: 商店相關功能
  - name: Transaction
    description: 交易相關功能
  - name: Product
    description: 產品相關功能
  - name: Contact
    description: 聯絡人相關功能

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 驗證需要的token
  parameters:
    language:
      in: header
      name: accept-language
      schema:
        type: string
      required: false
      example: 'en'
  schemas:
    BusinessInfoResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            name:
              type: string
              description: 商店名稱
            mobile:
              type: string
              description: 電話
            landmark:
              type: string
              description: 地址
            country:
              type: string
              description: 國家
            state:
              type: string
              description: 地區
            city:
              type: string
              description: 城市
            landmark:
              type: string
              description: 地址
            zip_code:
              type: string
              description: 郵遞區號
    OnDutyResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            user_id:
              type: number
              description: 店員 ID
            user_name:
              type: string
              description: 店員姓名
            pharmacist_id:
              type: number
              description: 藥劑師 ID
            pharmacist_name:
              type: string
              description: 藥劑師姓名
    TransactionsResponse:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: number
                description: 訂單編號
              pharmacist_name:
                type: string
                description: 藥師姓名
              prescription_sign_message:
                type: string
                description: 症狀
              username:
                type: string
                description: 使用者名稱
              contact_name:
                type: string
                description: 病人姓名
              created_at:
                type: string
                description: 訂單產生日期
    SingleTransactionResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: number
              description: 訂單編號
            created_at:
              type: string
              description: 訂單產生日期
            contact_id:
              type: number
              description: 病人 ID
            contact_dob:
              type: string
              description: 病人生日
            contact_name:
              type: string
              description: 病人姓名
            language:
              type: string
              description: 慣用語
            total_amount:
              type: string
              description: 總金額
    CreateTransaction:
      type: object
      properties:
        contact_id:  # 病人ID
          type: integer
          description: 病人 ID
        contact_name:
          type: string
          description: 病人姓名
        doctor_name:
          type: string
          description: 醫生姓名
        hospital_key:
          type: integer
        hospital_name:
          type: string
          description: 醫院名稱
        prescription_sign_created_at:
          type: string
          description: 配藥日期
        prescription_sign_message:
          type: string
          description: 處方簽症狀
        products:
          type: string
          description: 藥品清單
        contact_custom_field1:
          type: string
          description: 病人身分證字號
        contact_mobile:
          type: string
          description: 病人手機
        contact_custom_field2:
          type: string
          enum:
            - F
            - M
          description: 病人性別
        contact_dob:
          type: string
          description: 病人生日
        contact_custom_field3:
          type: string
          description: 病人藥物忌諱
        purchase_id:
          type: integer
          description: 購買人 id
        purchase_name:
          type: string
          description: 購買人姓名
        purchase_mobile:
          type: string
          description: 購買人電話
        purchase_identy_number:
          type: string
          description: 購買人身份證字號
      # Both properties are required
      required:  
        - contact_name
        - contact_custom_field1
    SuspendTransaction:
      type: object
      properties:
        contact_id:  # 病人ID
          type: integer
          nullable: true
          description: 病人 ID
        contact_name:
          type: string
          description: 病人姓名
        doctor_name:
          type: string
          description: 醫生姓名
        hospital_key:
          type: string
        hospital_name:
          type: string
          description: 醫院名稱
        prescription_sign_created_at:
          type: string
          description: 配藥日期
        prescription_sign_message:
          type: string
          description: 處方簽症狀
        products:
          type: string
          description: 藥品清單
        contact_custom_field1:
          type: string
          description: 病人身分證字號
        contact_mobile:
          type: string
          description: 病人手機
        contact_custom_field2:
          type: string
          enum:
            - F
            - M
          description: 病人性別
        contact_dob:
          type: string
          description: 病人生日
        contact_custom_field3:
          type: string
          description: 病人藥物忌諱
        purchase_id:
          type: integer
          nullable: true
          description: 購買人 id
        purchase_name:
          type: string
          description: 購買人姓名
        purchase_mobile:
          type: string
          description: 購買人電話
        purchase_identy_number:
          type: string
          description: 購買人身份證字號
        token:
          type: string
      # Both properties are required
      required:  
        - contact_name
        - contact_custom_field1
    CreateContact:
      type: object
      properties:
        type:
          type: string
          enum:
            - patient
            - customer
          description: 客戶類型 patient/customer
        accountNo:
          type: string
          description: 身分證字號
        address:
          type: string
          description: 地址
        allergyDrug:
          type: array
          items:
            type: string
          description: 藥物過敏
        drugNote:
          type: array
          items:
            type: string
          description: 藥物過敏備註
        allergyIngredient:
          type: array
          items:
            type: string
          description: 主成份過敏
        ingredientNote:
          type: array
          items:
            type: string
          description: 主成份過敏備註
        birthday:
          type: string
          description: 生日
        drugTaBoo:
          type: string
          description: 藥物忌諱
        email:
          type: string
          description: 電子信箱
        gender:
          type: string
          enum:
            - F
            - M
          description: 性別
        mobile:
          type: string
          description: 手機號碼
        name:
          type: string
          description: 姓名
        phoneNumber:
          type: string
          description: 電話
        language:
          type: string
          description: 慣用語
          default: "en"
      required:
        - type
        - name
    ContactsResponse:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: number
                description: 顧客 id
              type:
                type: string
                enum:
                  - patient
                  - customer
                  - p_and_c
                description: 顧客類型(病人 or 購買人)
              name:
                type: string
                description: 顧客名稱
              mobile:
                type: string
                description: 手機號碼
              accountNo:
                type: string
                description: 身分證字號
              created_at:
                type: string
                description: 建立日期
    SingleContactResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: number
              description: 顧客 id
            type:
              type: string
              enum:
                - patient
                - customer
                - p_and_c
              description: 顧客類型(病人 or 購買人)
            identity_id:
              type: string
              description: 身分證字號
            name:
              type: string
              description: 顧客名稱
            gender:
              type: string
              enum:
                - F
                - M
              description: 性別
            birthday:
              type: string
              description: 生日
            email:
              type: string
              description: email
            mobile: 
              type: string
              description: 手機號碼
            phoneNumber:
              type: string
              description: 電話號碼
            address:
              type: string
              description: 地址
            drugTaBoo:
              type: string
              description: 藥物忌諱
            allergyDrugs:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: integer
                    description: 藥品ID
                  note:
                    type: string
                    description: 藥品備註
              description: 藥品過敏
            allergyIngredients:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: integer
                    description: 主成份 ID
                  note:
                    type: string
                    description: 主成份過敏備註                          
              description: 主成份過敏
            created_at:
              type: string
              description: 建立日期
    SuspendResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            success:
              type: number
              description: success code
            msg:
              type: string
              description: response message
            transaction_id:
              type: number
              description: 暫存交易 id
    ProductsResponse:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: number
                description: 藥品 id
              sku:
                type: string
                description: 藥品 SKU
              name:
                type: string
                description: 藥品名稱
              qty_available:
                type: number
                description: 庫存數量
              alert_quantity:
                type: string
                description: 庫存警告數量
              default_sell_price:
                type: string
                description: 售價
              product_custom_field1:
                type: string
                description: 藥品證號
              product_custom_field2:
                type: string
                description: 藥品英文名稱
              product_custom_field3:
                type: string
                description: 藥廠
              product_custom_field4:
                type: string
                description: 藥品主成份
    SingleProductResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: number
              description: 藥品 id
            sku:
              type: string
              description: 藥品 SKU
            name:
              type: string
              description: 藥品名稱
            unit_key:
              type: string
              description: 單位 Key
            unit_short_name:
              type: string
              description: 單位簡稱
            qty_available:
              type: number
              description: 庫存數量
            alert_quantity:
              type: string
              description: 庫存警告數量
            default_sell_price:
              type: string
              description: 售價
            product_custom_field1:
              type: string
              description: 藥品證號
            product_custom_field2:
              type: string
              description: 藥品英文名稱
            product_custom_field3:
              type: string
              description: 藥廠
            product_custom_field4:
              type: string
              description: 藥品主成份

paths:
  /info:
    get:
      summary: Business Location 詳細資訊
      description: 會列出 Location 的詳細資訊
      tags:
        - Business
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessInfoResponse'
              example:
                data: 
                  name: A藥局
                  mobile: 0945761435
                  country: 香港
                  state: 尖沙嘴頂好北路50巷10號
                  city: 九龍
                  zip_code: 111
                  landmark: 好北路50巷10號
  /on-duty:
    get:
      summary: 值班人員
      description: 取得值班店員與值班藥師資訊
      tags:
        - Business
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OnDutyResponse'
              example:
                data:
                  usage_id: 1
                  user_name: A店員
                  pharmacist_id: 2
                  pharmacist_name: 陳藥劑師
  /transactions:
    get:
      summary: 交易清單
      description: 取得交易清單
      tags:
        - Transaction
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: contactId  # 身分證字號
          schema:
            type: integer
          description: Search contact for transactions
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionsResponse'
              example:
                data:
                  - id: 180
                    pharmacist_name: 陳藥師
                    prescription_sign_message: 頭痛
                    username: A店員
                    contact_name: A病人
                    created_at: 2022-10-21 09:33:52
                  - id: 181
                    pharmacist_name: 王藥師
                    prescription_sign_message: 胸悶
                    username: B店員
                    contact_name: B病人
                    created_at: 2022-10-30 09:33:52
    post:
      summary: 建立一筆交易.
      tags:
        - Transaction
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CreateTransaction'
            example:
              contact_id: 4
              contact_name: 桂綸鎂
              doctor_name: 王醫師
              hospital_key: 8
              hospital_name: 中九龍診所
              prescription_sign_created_at: 2022-10-20
              prescription_sign_message: 頭痛
              products:
              contact_custom_field1: A12345678
              contact_mobile: 0962875124
              contact_custom_field2: F
              contact_dob: 1990/1/20
              contact_custom_field3: 八角
              purchase_id: 8
              purchase_name: 戴立忍
              purchase_mobile: 09937645284
              purchase_identy_number: B8230185284
      responses:
        '200':
          description: Created
  /transactions/{id}:
    get:
      summary: 單一交易
      description: 取得單一交易資訊
      tags:
        - Transaction
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID of transaction to return
          required: true
          example: 126
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SingleTransactionResponse'
              example:
                data:
                  id: 258
                  created_at: 2022-11-08
                  contact_id: 45
                  contact_dob:
                  contact_name: "林志玲"
                  language: en
                  total_amount: 125.0000
  /transactions/{id}/products:
    get:
      summary: 交易表裡的產品清單
      description: 取得交易表裡的產品清單
      tags:
        - Transaction
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID of transaction to return
          required: true
          example: 126
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        sell_id:
                          type: number
                        quantity:
                          type: number
                        price:
                          type: string
                        usage_id:
                          type: number
                        product_id:
                          type: number
                        days:
                          type: number
                        total:
                          type: number
                        dosage:
                          type: number
                        frequency:
                          type: number
                        cautions:
                          type: array
                          items:
                            type: object
                        custom_caution:
                          type: string
                        dosage_form:
                          type: string
                        unit:
                          type: string
                        usage:
                          type: number
                  links:
                    type: object
                    properties:
                      first:
                        type: string
                      last:
                        type: string
                      prev:
                        type: string
                      next:
                        type: string
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: number
                      from:
                        type: number
                      last_page:
                        type: number
                      path:
                        type: string
                      per_page:
                        type: number
                      to:
                        type: number
                      total:
                        type: number
  /transactions/suspend:
    post:
      summary: 暫存交易
      tags:
        - Transaction
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SuspendTransaction'
            example:
              contact_id: 4
              contact_name: Willy01
              doctor_name: 
              hospital_key: 
              hospital_name: 
              prescription_sign_created_at: 2022-11-23
              prescription_sign_message: 頭痛
              products: [{"days":6,"total":6,"dosage":1,"frequency":"take_in_morning","product_id":11,"cautions":[],"custom_caution":"","dosage_form":"tablet","unit":"ml","usage":"oral"}]
              contact_custom_field1: A11111
              contact_mobile: 09123456
              contact_custom_field2: M
              contact_dob: 
              contact_custom_field3: 
              purchase_id: null
              purchase_name: 
              purchase_mobile: 
              purchase_identy_number: 
              token:
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuspendResponse'
  /products:
    get:
      summary: 產品清單
      description: "取得產品清單"
      tags:
        - Product
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: keyword
          schema:
            type: string
          description: The keyword for search products
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductsResponse'
              example:
                date:
                - id: 1
                  sku: SKU123
                  name: 眼藥水
                  qty_available: 200
                  alert_quantity: 10
                  default_sell_price: 125.000
                  product_custom_field1: HK-58956
                  product_custom_field2: S.T. NATURAL TEARS EYE DROPS
                  product_custom_field3: BIO
                  product_custom_field4: Vintamic C
                - id: 2
                  sku: SKU223
                  name: 暈船藥
                  qty_available: 250
                  alert_quantity: 15
                  default_sell_price: 110.000
                  product_custom_field1: HK-68741
                  product_custom_field2: S.T. NATURAL TEARS EYE DROPS
                  product_custom_field3: BIO
                  product_custom_field4: Vintamic C
                links:
                  type: object
                  properties:
                    first:
                      type: string
                    last:
                      type: string
                    prev:
                      type: string
                    next:
                      type: string
                meta:
                  type: object
                  properties:
                    current_page:
                      type: number
                    from:
                      type: number
                    last_page:
                      type: number
                    path:
                      type: string
                    per_page:
                      type: number
                    to:
                      type: number
                    total:
                      type: number
  /products/{id}:
    get:
      summary: '取得單一產品'
      description: 取得單一產品詳細資訊
      tags:
        - Product
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID of product to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SingleProductResponse'
  /contacts:
    get:
      summary: 客戶清單
      description: 取得客戶清單
      tags:
        - Contact
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: accountNo
          schema:
            type: string
          description: 身分證字號
        - in: query
          name: neme
          schema:
            type: string
          description: 客戶姓名
        - in: query
          name: mobile
          schema:
            type: string
          description: 手機號碼
        - in: query
          name: keyword
          schema:
            type: string
          description: 關鍵字(搜尋 客戶姓名,手機號碼跟身分證字號)
        - in: query
          name: type
          schema:
            type: string
            enum:
              - patient
              - customer
              - p_and_c
          description: 客戶類型
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactsResponse'
              example:
                data:
                  - id: 20
                    type: customer
                    name: 王大明
                    mobile: 0934987146
                    accountNo: Z12345678
                    created_at: 2022-10-21
                  - id: 21
                    type: patient
                    name: 林小美
                    mobile: 0933167832
                    accountNo: S76893542
                    created_at: 2022-10-21
                links:
                  type: object
                  properties:
                    first:
                      type: string
                    last:
                      type: string
                    prev:
                      type: string
                    next:
                      type: string
                meta:
                  type: object
                  properties:
                    current_page:
                      type: number
                    from:
                      type: number
                    last_page:
                      type: number
                    path:
                      type: string
                    per_page:
                      type: number
                    to:
                      type: number
                    total:
                      type: number
    post:
      summary: '建立病人/購買人資訊'
      description: 建立病人/購買人資訊
      tags:
        - Contact
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CreateContact'
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                      contactId:
                        type: number
                        description: 顧客 id
                      success:
                        type: boolean
                        description: 是否成功
  /contacts/{id}:
    get:
      summary: '取得單一客戶資訊'
      description: 取得單一客戶詳細資訊
      tags:
        - Contact
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID of contact to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SingleContactResponse'
              example:
                data:
                  id: 20
                  type: customer
                  identity_id: "3412753"
                  name: A病人
                  gender: M
                  birthday: 2022-09-07
                  email: allen@nextgen.com.hk
                  mobile: 0934184625
                  phoneNumber: 07 654876
                  address: 大安區, 台北市, 台灣 11033
                  drugTaBoo: 八角
                  allergyDrugs:
                    - id: 2038
                      note: "頭痛"
                    - id: 2058
                      note: "心悸"
                  allergyIngredients:
                    - id: 1038
                      note: "胸痛"
                    - id: 1058
                      note: "眼痛"
                  created_at: 2022-10-21

    put:
      summary: '更新病人/購買人資訊'
      description: 更新病人/購買人資訊
      tags:
        - Contact
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID of contact to return
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CreateContact'
            example:
              type: patient
              accountNo: A12345678
              address: 九龍灣
              allergyDrug: [5048, 5059]
              drugNote: ['想睡', '肌肉酸痛']
              allergyIngredient: [2012, 3023]
              ingredientNote: ["頭暈", "肌肉酸痛"]
              birthday: 2022-10-1
              drugTaBoo: 消炎藥
              email: abcdefg@nextgen.com.hk
              gender: F
              mobile: 0911765872
              name: 桂綸鎂
              phoneNumber: 025438762
      responses:
        '200':
          description: Created
    
